### ISSUE TITLE
How to make login session persist?

### ISSUE THREAD

**Issue by pkonduri** [tylerjrichards/st-paywall#44] opened 2023-11-06 19:37 UTC
When a user logs in (by clicking the `Login with Google` button), and then refreshes the page, they are asked to login again. How do we make this login state persist across website refreshes? 

This issue can be seen in the https://subscription.streamlit.app/ app

**Comment by jozkotrapko** [comment] 2023-11-10 15:35
If I'm not mistaken, streamlit doesn't provide cookies and that's why the user loses the login after refreshing the page.

**Comment by tylerjrichards** [comment] 2023-11-11 20:11
yeah this is exactly it, i've been trying to add it to cookies but that doesn't work either, because then someone could just edit their cookies to someone who is subscribed and get in easily. So it would be way less secure that way.

**Comment by tylerjrichards** [comment] 2023-11-11 20:11
closing this as it is a dupe of https://github.com/tylerjrichards/st-paywall/issues/23

**Closed by tylerjrichards** 2023-11-11 20:11 UTC
