### ISSUE TITLE
Streamlit app continues even with Gmail accounts not on the test list

### ISSUE THREAD

**Issue by ibehnam** [tylerjrichards/st-paywall#30] opened 2023-08-30 03:25 UTC
I have added only one gmail account to my test list in Google Web Apps, but I can login using any other gmail account (!) and the Streamlit app continues running after `add_aut(required=True)`.

**Comment by jozkotrapko** [comment] 2023-11-11 14:29
I assume it will sign you up automatically, but it won't bypass the subscription. Try another browser or incognito mode.

**Comment by sfc-gh-trichards** [comment] 2023-11-11 20:02
I can't reproduce this behavior at all (see video), can one of you give me a video / reproducible example for this?

https://github.com/tylerjrichards/st-paywall/assets/103017176/1dee3c40-974a-42d5-abc1-32811e2aff19

**Comment by jozkotrapko** [comment] 2023-11-11 20:13
> I can't reproduce this behavior at all (see video), can one of you give me a video / reproducible example for this?
> 
>  CleanShot.2023-11-11.at.12.01.27.mp4

https://github.com/tylerjrichards/st-paywall/assets/85027659/ad403806-6da1-4535-b0b1-ae2151c49d1a

**Comment by tylerjrichards** [comment] 2023-11-11 20:26
I don't think I fully understand what is going on here, so are you saying users should stay logged in cross browser? Or what is the actual issue?

**Comment by jozkotrapko** [comment] 2023-11-11 20:35
When I click the sign in button on microsoft edge, google doesn't ask me which account I want to sign in with.

**Comment by jozkotrapko** [comment] 2023-11-11 20:41
The mistake is on my side, google is automatically signing up one account, the only one signed in w google... I deleted the previous messages, I apologize for the mistake that occurred on my side and for the unnecessary delay of your time...

**Comment by tylerjrichards** [comment] 2023-11-11 20:49
literally don't worry about it at all, i'm going to close this issue unless it can be reproduced! thanks for trying it out @jozkotrapko

**Closed by tylerjrichards** 2023-11-11 20:49 UTC
